# Generated by Django 5.0.6 on 2024-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
